# Generated by Django 5.0.7 on 2024-07-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0002_incident'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='Reporter_Name',
        ),
        migrations.AddField(
            model_name='incident',
            name='TITILE_OF_INCIDENT',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
